### ISSUE TITLE
LibraryPath + IncludePath

### ISSUE THREAD

**Issue by Voskrese** [zufuliu/llvm-utils#1]
неверные пути

> Note: If your LLVM version is not 7.0, please change $(LLVMInstallDir)\lib\clang\7.0\ in each Toolset.props to appropriate value.

...
исправить на \7.0.0\
```
  <PropertyGroup>
....
    <IncludePath>$(LLVMInstallDir)\lib\clang\7.0.0\include;$(IncludePath)</IncludePath>
    <LibraryPath>$(LLVMInstallDir)\lib\clang\7.0.0\lib\windows;$(LibraryPath)</LibraryPath>
  </PropertyGroup>
```

**Comment by zufuliu** [comment]
As it says, look at `LLVM Install Directory`, under `lib\clang` folder, the folder name is the version number.
