### ISSUE TITLE
Update llvm-link.bat for LLVM 19

### ISSUE THREAD

**Issue by gitoss** [zufuliu/llvm-utils#15]
As of LLVM 19.1.2, there are a couple of other identical files that could be dedupe'd using https://github.com/zufuliu/llvm-utils/blob/main/llvm/llvm-link.bat

EDIT: ONLY for the (slower) -Windows-X64.tar.xz version, for the (faster) -x86_64-pc-windows-msvc.tar.xz ... see below.

```
DEL llvm-boltdiff.exe perf2bolt.exe
MKLINK llvm-boltdiff.exe llvm-bolt.exe
MKLINK perf2bolt.exe llvm-bolt.exe

DEL llvm-bitcode-strip.exe llvm-install-name-tool.exe llvm-objcopy.exe
MKLINK llvm-bitcode-strip.exe llvm-strip.exe
MKLINK llvm-install-name-tool.exe llvm-strip.exe
MKLINK llvm-objcopy.exe llvm-strip.exe

DEL llvm-otool.exe
MKLINK llvm-otool.exe llvm-objdump.exe

DEL llvm-readelf.exe
MKLINK llvm-readelf.exe llvm-readobj.exe

DEL llvm-windres.exe
MKLINK llvm-windres.exe llvm-rc.exe
```

**Comment by zufuliu** [comment]
> do you know

It's explained here at https://discourse.llvm.org/t/llvm-19-x-release-third-party-binaries/80374/30

**Comment by zufuliu** [comment]
> There are a couple of more dupes than in the current llvm-del.bat script - but someone would have to double-check the overlap with the more/other dupes in -Windows-X64.tar.xz if the script would have to work for both...

Handled by commit 755ab29170b2e2dde36998478c230b993f431931 and 4e761af15c4cc856b4acb5be58b16d570dfee04b.
