### ISSUE TITLE
Generated solution does not recompile modified files

### ISSUE THREAD

**Issue by jpursey** [zufuliu/llvm-utils#4]
Manually recompiling a source file, will trigger the linker to pick up the new .obj and build the .exe, but changing the source file and building does not regenerate the obj.

I am using: 
- Microsoft Visual Studio Community 2019, Version 16.8.4
- clang version 11.0.1, target: x86_64-pc-windows-msvc

**Comment by zufuliu** [comment]
This is a limitation for Clang, you will need to rebuild whole project. see https://bugs.llvm.org/show_bug.cgi?id=37187

**Comment by jpursey** [comment]
Ok, I will follow progress over there (although it does not seem to be a priority from the age of the thread). Visual Studio's own CMake support with clang does not seem to have this problem (perhaps because the build itself seems to be driven by Ninja).

**Comment by zufuliu** [comment]
You can also use this toolchain in CMake, see issue #2.
The problem for project files seems because clang only implemented old style PDB file, see comments at https://github.com/zufuliu/llvm-utils/blob/master/VS2017/LLVM/LLVM.Common.targets#L109
