### ISSUE TITLE
Example for CI builds

### ISSUE THREAD

**Issue by MohitSethi99** [zufuliu/llvm-utils#8]
Got it working on my machine, just did VS2017/install.bat and it worked like charm, now I can manually change toolset to use LLVM_v143 and it works.
But the problem is with CI builds, how will I change the toolset there? Can you please provide an example for that?
My current build pipeline includes making vs project files with premake and building the generated solution with msbuild.

**Comment by zufuliu** [comment]
see https://github.com/zufuliu/notepad2 for running instance on AppVeyor and GitHub Actions.
I just created project configurations (see https://github.com/zufuliu/notepad2/blob/main/build/VS2017/Notepad2.vcxproj#L150) for LLVM_vxxx  toolset.

**Comment by MohitSethi99** [comment]
Got it. I think it's more of a premake issue than llvm-utils.
Anyways, great little tool, thanks a ton for the support.
