### ISSUE TITLE
Visual Studio fails to respond to disable/enable select code paths with Preprocessor __clang__ and/or __llvm__

### ISSUE THREAD

**Issue by MohitSethi99** [zufuliu/llvm-utils#9]
Issue: 
```cpp
#if defined(__clang__)
//this code won't execute
#endif
```

**Comment by zufuliu** [comment]
https://godbolt.org/z/n4vf9x54r

**Comment by zufuliu** [comment]
You probably handled `_MSC_VER` first which clang-cl also defines.

**Comment by MohitSethi99** [comment]
You're right, it does work but Visual Studio fails to reflect it in the editor.
VS clang cl manages to correctly disables the code in the editor.

LLVM_v43:
![image](https://user-images.githubusercontent.com/29519295/210229350-2b275d78-19f7-497f-b0e5-a16df61989d7.png)

LLVM - clang-cl (Visual Studio addon):
![image](https://user-images.githubusercontent.com/29519295/210229648-f91a3426-b82d-493f-ab0e-4d524882d57a.png)

**Comment by zufuliu** [comment]
There may needs further work as Visual Studio Code Analysis or IntelliSense doesn't understand clang extension.
e.g. for https://github.com/zufuliu/notepad2/blob/main/src/EditAutoC.c
There are 40 errors with `LLVM_v143` (more errors with `LLVM (clang-cl)`).
![LLVM_v143](https://user-images.githubusercontent.com/2289926/210543860-775019f4-b03a-4714-8c21-51e018cb316f.png)
![LLVM_clang-cl](https://user-images.githubusercontent.com/2289926/210543894-cf0c7772-a3f2-4d5b-8eaa-4adab3ec2a40.png)
